spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8090
  servlet.context-path: /employee-service
  shutdown: "graceful"